name = "xlunas-stream-api"
account_id = "bf61388e0aed5ce0f0784a08206619b3"
compatibility_date = "2025-05-16"

[vars]
STREAM_ACCOUNT_ID = "bf61388e0aed5ce0f0784a08206619b3"

[experimental]
  upload_requirements = { format = "modules" }
